apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus
  namespace: devops-toolsss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus-server
  template:
    metadata:
      labels:
        app: nexus-server
    spec:
      containers:
        - name: nexu
          image: sonatype/nexus3:latest
          ports:
            - containerPort: 8081
          volumeMounts:
            - mountPath: /nexus-data
              name: nexus-data
      volumes:
        - name: nexus-data
          emptyDir: {}
