apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nexus
  namespace: {{ .Release.Namespace }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - backend:
              serviceName: {{ .Values.label }}
              servicePort: {{ .Values.service.port }}