apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.label }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Values.label }}
  type: LoadBalancer
  ports:
    - port: {{ .Values.service.port }}
      protocol: {{ .Values.service.protocol }}
      targetPort: {{ .Values.container.port }}